spring:
  aop:
    proxy-target-class: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/web_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 9090

mybatis-plus:
  global-config:
    db-config:
      db-type: mysql

logging:
  path:../logs